# ------------------------------------- #
# ---- General Settings --------------- #
# ------------------------------------- #
baseURL = "/"
title = "Wing"
theme = "den"
enableRobotsTXT = true       # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
rssLimit = 20                # limit number of entries in RSS feeds
paginate = 20
paginatePath = "page"

# Syntax Hightlight
PygmentsCodeFences = true
PygmentsUseClasses = true    # required for shhighlight shortcode

# service plugins
disqusShortname = ""         # disqus_shortname
googleAnalytics = ""         # UA-XXXXXXXX-X

contentDir = "content"

# language support # en / zh-tw / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # Default language to use
# defaultContentLanguageInSubdir = false

# Links format
[permalinks]
  posts = "/:year/:month/:day/:slug/"
  categories = "/category/:slug/"      # required
  tags = "/tag/:slug/"                 # required
  pages = "/:slug/"

[author]                     # required
  name = "Pan Feng"

[sitemap]                    # required
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# ------------------------------------- #
# ---- Other Params ------------------- #
# ------------------------------------- #

[params]
  since = "2017"             # Site creation time
  rssFullContent = true      # set true to use full content instead of summary
  # site info (optional)
  description = "不断拓展傍身之术，不忘探寻心中之道"
  logoTitle = "Wing" # shown on top-left, default: title
  headerTitle = "Wing"                   # default: title
  customFavicon = "https://cdn.jsdelivr.net/gh/fy975713384/cloud-img@main/blog/wing_icon.png"
  # siteLogoImage = "images/wing_icon.png"     # shown besides logoTitle
  headerImage = "https://cdn.jsdelivr.net/gh/fy975713384/cloud-img@main/blog/background.jpg"
  showAuthorCard = true # Whether to show author information below the article

  showMenuLanguages = true

  autoLoadComments = false # auto load comment when scrolling down

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  google_verification = ""  # Google_Verification

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']             # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []              # if ['custom.js'], load '/static/js/custom.js' file

[params.comments]
  owner = "fy975713384"
  repo = "fy975713384.github.io"
  clientID = "35afb85e4c521d6dbeb8"
  clientSecret = "463c9ec266980fd7358a11479beda5284ecf9f71"

# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 50

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
    name = "categories"
    weight = 200

  [[related.indices]]
    name = "keywords"
    weight = 150

  [[related.indices]]
    name = "tags"
    weight = 100

# ---------------- #
# ---- menu ------ #
# ---------------- #

[menu]
  [[menu.main]]
    name = "笔记"
    weight = 10
    identifier = "notes"
    url = "category/notes/"

  [[menu.main]]
    name = "游记"
    weight = 20
    identifier = "travals"
    url = "category/travals/"

  [[menu.social]]
    name = "GitHub"
    weight = 10
    identifier = "github"
    url = "https://github.com/fy975713384"
  
  [[menu.social]]
    name = "联系我"
    weight = 11
    identifier = "email"
    url = "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=NFVOQVgaUnRSW0xZVV1YGldbWQ"
  
  [[menu.links]]
    name = "关于我"
    weight = 10
    identifier = "about-me"
    url = "/"

  [[menu.links]]
    name = "简书主页"
    weight = 10
    identifier = "jianshu"
    url = "https://www.jianshu.com/u/a479a910abe7"
